# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: t.vyas1601@gmail.com
author_name: Vyas
contract_name: algosphere_core
deployment_language: python
preset_name: starter
project_name: AlgoSphere

